// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var about, contact, projects, skills;
    $(document).on("go", function() {
      return $('.footer ul').fadeIn("slow", function() {
        return $('.logo').fadeIn("slow", function() {
          return $('.nav').fadeIn("slow", function() {
            return $(document).trigger('done');
          });
        });
      });
    });
    $(".cmd").on('click', function() {
      var e, input;
      input = $('input#command').last();
      e = $.Event('keyup');
      e.which = 13;
      return input.val($(this).text()).focus().trigger(e);
    });
    $(document.body).click(function() {
      var input;
      input = $('input#command').last();
      return input.focus();
    });
    about = $('#about');
    projects = $('#projects');
    skills = $('#skills');
    contact = $('#contact');
    $(document).on('about', function() {
      if (about.hasClass('active')) {
        return;
      }
      if (skills.hasClass('active')) {
        skills.fadeOut('fast').removeClass('active');
        return setTimeout((function() {
          return about.fadeIn().addClass('active');
        }), 200);
      } else {
        return about.fadeIn().addClass('active');
      }
    });
    $(document).on('skills', function() {
      if (skills.hasClass('active')) {
        return;
      }
      if (about.hasClass('active')) {
        about.fadeOut('fast').removeClass('active');
        return setTimeout((function() {
          return skills.fadeIn().addClass('active');
        }), 200);
      } else {
        return skills.fadeIn().addClass('active');
      }
    });
    $(document).on('projects', function() {
      if (projects.hasClass('active')) {
        return;
      }
      if (contact.hasClass('active')) {
        contact.fadeOut('fast').removeClass('active');
        return setTimeout((function() {
          return projects.fadeIn().addClass('active');
        }), 200);
      } else {
        return projects.fadeIn().addClass('active');
      }
    });
    return $(document).on('contact', function() {
      if (contact.hasClass('active')) {
        return;
      }
      if (projects.hasClass('active')) {
        projects.fadeOut('fast').removeClass('active');
        return setTimeout((function() {
          return contact.fadeIn().addClass('active');
        }), 200);
      } else {
        return contact.fadeIn().addClass('active');
      }
    });
  });

}).call(this);
